name: Revision IA de PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  revisar_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar GitHub CLI
        uses: cli/cli-action@v2

      - name: Obtener commits y diff del PR
        run: |
          gh pr view ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --json commits > commits.json
          gh pr diff ${{ github.event.pull_request.number }} --repo ${{ github.repository }} > pr_diff.txt

      - name: Instalar dependencias
        run: pip install google-generativeai

      - name: Ejecutar revisión con Gemini
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python3 .github/scripts/revision_ia.py commits.json pr_diff.txt
