name: Revisión IA de PR

on:
  pull_request:

jobs:
  revisar_pr:
    runs-on: ubuntu-latest
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GOOGLE_API_USE_REST: "true"
    steps:
      - uses: actions/checkout@v3

      - name: Instalar dependencias
        run: pip install -U google-generativeai requests

      - name: Ejecutar revisión IA
        run: |
          export PR_NUMBER=${{ github.event.pull_request.number }}
          python .github/scripts/revision_ia.py
